# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Deploy

on:
- push
- workflow_dispatch
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        settings-path: ${{ github.workspace }} # location for the settings.xml file
  
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Deploy
      env:
        GITHUB_TOKEN: ${{github.token}}
        BRANDIZI_REPO_USER: ${{secrets.BRANDIZI_REPO_USER}}
        BRANDIZI_REPO_PWD: ${{secrets.BRANDIZI_REPO_PWD}}
        CI_PULL_REQUEST: ${{ github.event.pull_request.number }}
                 
      run: ./ci-build.sh
        